export const constants = {
    SET_IMAGES: 'SET_IMAGES',
    ADD_IMAGES: 'ADD_IMAGES',
    IMAGES_REQUEST: 'IMAGES_REQUEST',
    IMAGES_LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    IMAGES_LOAD_FAILURE: 'IMAGES_LOAD_FAILURE',
    SET_CLIENT_QUERY: 'SET_CLIENT_QUERY',
    SET_TOTAL_HITS: 'SET_TOTAL_HITS'
}